# GitHub仓库配置
target_repo: "commit-doc-verifier"
target_branch: "main"
feature_doc_path: "docs/features.md"

# 表格配置
table_header: "| 功能名称 | SHA | 作者 | 分支 | 日期 | 改动文件数 | 提交消息 |"

# 文档结构验证
required_sections:
  - "## 功能提交跟踪"
  - "## 项目概述"
  - "## 功能提交记录"
  - "### 提交表格"
  - "## 提交统计"
  - "## 质量指标"
  - "## 后续计划"

# 特征数量验证
min_feature_count: 3

# 预期特征验证（与features.md表格完全匹配）
expected_features:
  "用户认证功能": "a1b2c3d4"
  "数据导出功能": "e5f6g7h8"
  "报表生成功能": "i9j0k1l2"

# 预期作者验证（SHA必须与表格一致）
expected_authors:
  "a1b2c3d4": "johnsmith"
  "e5f6g7h8": "alicejones"
  "i9j0k1l2": "bobwilson"

# 预期消息验证（必须完全匹配表格内容）
expected_messages:
  "a1b2c3d4": "实现用户登录和注册功能"
  "e5f6g7h8": "添加CSV数据导出功能"
  "i9j0k1l2": "实现月度报表自动生成"

# 预期日期验证（格式必须为YYYY-MM-DD）
expected_dates:
  "a1b2c3d4": "2024-01-15"
  "e5f6g7h8": "2024-01-16"
  "i9j0k1l2": "2024-01-17"